import java.io.*;
class bawaji94test1
{
	public static void main(String args[])throws IOException
	{
		BufferedReader br=new BufferedReader(new InputStreamReader(System.in));
		char array[][][]=new char[20][20][9];
		int x[]=new int[400];
		int y[]=new int[400];
		String s=br.readLine();
		int i,j,k,i1=0,i2=0,i3=0,j1=0,j2=0,j3=0;
		for(i=0;i<20;i++)
		{
			for(j=0;j<20;j++)
			{
				for(k=0;k<9;k++)
				{
					array[i][j][k]=s.charAt(i*9*20+j*9+k);
				}
			}
		}
		int count=0;
		for(i=0;i<20;i++)
		{
			if(array[i][0][0]!='0')
			{
				count++;
			}
		}
		if(count==0)
		{
			System.out.print("10,0,10,1");
		}
		else
		{
			count=0;
			for(i=0;i<20;i++)
			{
				for(j=0;j<20;j++)
				{
					if(array[i][j][0]=='1')
					{
						x[count]=i;
						y[count]=j;
						count++;
					}
				}
			}
			int dir=0;
			for(i=1;i<9;i++)
			{
				if(array[x[0]][y[0]][i]=='0')
				{
					if(i==1)
					{
						if(dir==0)
						{
							i2=x[0]-1;
							j2=y[0];
						}
						if(dir==1)
						{
							i3=x[0]-1;
							j3=y[0];
						}
					}
					if(i==2)
					{
						if(dir==0)
						{
							i2=x[0]-1;
							j2=y[0]+1;
						}
						if(dir==1)
						{
							i3=x[0]-1;
							j3=y[0]+1;
						}
					}
					if(i==3)
					{
						if(dir==0)
						{
							i2=x[0];
							j2=y[0]+1;
						}
						if(dir==1)
						{
							i3=x[0];
							j3=y[0]+1;
						}
					}
					if(i==4)
					{
						if(dir==0)
						{
							i2=x[0]+1;
							j2=y[0]+1;
						}
						if(dir==1)
						{
							i3=x[0]+1;
							j3=y[0]+1;
						}
					}
					if(i==5)
					{
						if(dir==0)
						{
							i2=x[0]+1;
							j2=y[0];
						}
						if(dir==1)
						{
							i3=x[0]+1;
							j3=y[0];
						}
					}
					if(i==6)
					{
						if(dir==0)
						{
							i2=x[0]+1;
							j2=y[0]-1;
						}
						if(dir==1)
						{
							i3=x[0]+1;
							j3=y[0]-1;
						}
					}
					if(i==7)
					{
						if(dir==0)
						{
							i2=x[0];
							j2=y[0]-1;
						}
						if(dir==1)
						{
							i3=x[0];
							j3=y[0]-1;
						}
					}
					if(i==8)
					{
						if(dir==0)
						{
							i2=x[0]-1;
							j2=y[0]-1;
						}
						if(dir==1)
						{
							i3=x[0]-1;
							j3=y[0]-1;
						}
					}
					dir++;
				}
				if(dir==2)
				{
					break;
				}
			}
			System.out.print(x[0]+","+y[0]+","+i2+","+j2+","+i3+","+j3);
		}
	}
}